server:
  port: 8880
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: 30 # Seconds
  
database:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  dbname: tracker-api
  sslmode: disable
  schema: public

security:
  expiredToken: 24 # Hour
  refreshToken: 50 # Min
  jwtsecret: 5C9ftETJIGDaxpd4DawcyEVenMDDM3gn

langs:
  - "en" # default
  - "th"
  - "fr"